import type {
  CoverageStatus,
  Payer,
  ClinicalCriteria,
  PlanCard,
  DiagnosisOption,
  PolicyChange,
  QuarterOption,
} from "./types";

// Re-export types for backward compatibility
export type { CoverageStatus, Payer, ClinicalCriteria, PlanCard, DiagnosisOption, PolicyChange, QuarterOption };

export const DIAGNOSIS_OPTIONS: DiagnosisOption[] = [
  { value: "C34.90", label: "C34.90 — Non-small cell lung cancer" },
  { value: "C43.9", label: "C43.9 — Malignant melanoma" },
  { value: "C50.919", label: "C50.919 — Breast cancer" },
  { value: "C18.9", label: "C18.9 — Colorectal cancer" },
  { value: "M06.9", label: "M06.9 — Rheumatoid arthritis" },
  { value: "L40.0", label: "L40.0 — Psoriasis vulgaris" },
  { value: "K50.90", label: "K50.90 — Crohn's disease" },
  { value: "G35", label: "G35 — Multiple sclerosis" },
];

export const MOCK_PLANS: PlanCard[] = [
  // Keytruda
  {
    id: "aetna-keytruda",
    payer: "Aetna",
    drugName: "Keytruda",
    rxNormCode: "RxNorm:1657973",
    coverageStatus: "Prior Auth Required",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["C34.90", "C43.9", "C50.919"],
    criteria: {
      trialDuration: "Must have failed 3-month trial of standard chemotherapy",
      labRequirements: ["PD-L1 expression ≥ 50% (TPS)", "EGFR/ALK negative status confirmed"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "FDA-approved indications only; PD-L1 tumor proportion score required",
      additionalNotes: "Re-authorization required every 12 months. Maximum 24 months of therapy unless clinical justification provided.",
      sourceSnippet: "Section 4.2.1 — Pembrolizumab (Keytruda): Prior authorization is required for all indications. Member must demonstrate PD-L1 TPS ≥ 50% via FDA-approved companion diagnostic. Trial of platinum-based chemotherapy × 3 months required for first-line NSCLC.",
      sourceDocLink: "#aetna-formulary-2026.pdf",
    },
  },
  {
    id: "uhc-keytruda",
    payer: "UHC",
    drugName: "Keytruda",
    rxNormCode: "RxNorm:1657973",
    coverageStatus: "Prior Auth Required",
    effectiveDate: "2026-01-15",
    diagnosisCodes: ["C34.90", "C43.9"],
    criteria: {
      trialDuration: "Must have failed 6-month trial of first-line platinum doublet",
      labRequirements: ["PD-L1 expression ≥ 1% (CPS)", "Microsatellite instability (MSI) testing"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "Limited to NSCLC and melanoma; additional indications require peer-to-peer review",
      additionalNotes: "Re-authorization every 6 months. Quantity limit of 200mg per 3-week cycle.",
      sourceSnippet: "UHC Clinical Policy Bulletin 2026-CP-0194: Pembrolizumab requires PA. First-line NSCLC: 6-month platinum doublet failure required. PD-L1 CPS ≥ 1%. Reauth q6 months with imaging.",
      sourceDocLink: "#uhc-clinical-policy-2026.pdf",
    },
  },
  {
    id: "cigna-keytruda",
    payer: "Cigna",
    drugName: "Keytruda",
    rxNormCode: "RxNorm:1657973",
    coverageStatus: "Preferred",
    effectiveDate: "2025-07-01",
    diagnosisCodes: ["C34.90", "C43.9", "C50.919", "C18.9"],
    criteria: {
      trialDuration: "No prior therapy trial required for first-line use in approved indications",
      labRequirements: ["PD-L1 testing recommended but not required", "Tumor genomic profiling encouraged"],
      ageLimit: "12 years and older (pediatric indications included)",
      diagnosisRequirement: "All FDA-approved indications covered; NCCN compendium indications accepted",
      additionalNotes: "Preferred specialty drug. No quantity limits. Auto-renewal for active patients.",
      sourceSnippet: "Cigna Formulary 2025-2026, Tier 2 Specialty: Pembrolizumab — Preferred status. No step therapy. PA waived for FDA/NCCN indications. Covers pediatric MSI-H/dMMR indications per label.",
      sourceDocLink: "#cigna-formulary-2025-2026.pdf",
    },
  },
  // Humira
  {
    id: "aetna-humira",
    payer: "Aetna",
    drugName: "Humira",
    rxNormCode: "RxNorm:327361",
    coverageStatus: "Step Therapy",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["M06.9", "L40.0", "K50.90"],
    criteria: {
      trialDuration: "Must fail 3-month trial of methotrexate AND one conventional DMARD",
      labRequirements: ["TB screening (QuantiFERON-TB Gold)", "Hepatitis B/C panel", "CBC with differential"],
      ageLimit: "18 years and older for RA; 6+ for JIA",
      diagnosisRequirement: "Documented moderate-to-severe disease activity (DAS28 ≥ 3.2 for RA)",
      additionalNotes: "Biosimilar preferred over brand. Step-through biosimilar required effective Q2 2026.",
      sourceSnippet: "Aetna Pharmacy Management: Adalimumab — Step therapy required. Step 1: Methotrexate × 3 months + 1 conventional DMARD. Step 2: Preferred biosimilar (Hadlima/Hyrimoz). Step 3: Brand Humira with clinical justification.",
      sourceDocLink: "#aetna-biologic-policy-2026.pdf",
    },
  },
  {
    id: "uhc-humira",
    payer: "UHC",
    drugName: "Humira",
    rxNormCode: "RxNorm:327361",
    coverageStatus: "Prior Auth Required",
    effectiveDate: "2026-02-01",
    diagnosisCodes: ["M06.9", "L40.0", "K50.90"],
    criteria: {
      trialDuration: "Must fail 6-month trial of methotrexate or documented intolerance",
      labRequirements: ["TB screening", "Hepatitis panel"],
      ageLimit: "4 years and older",
      diagnosisRequirement: "Active moderate-to-severe disease; physician attestation required",
      additionalNotes: "Brand Humira covered. No biosimilar step required. 90-day supply preferred via specialty pharmacy.",
      sourceSnippet: "UHC Prior Auth Form PA-BIO-2026: Adalimumab (Humira). MTX trial × 6 months or documented contraindication. TB negative within 6 months. Reauth annually.",
      sourceDocLink: "#uhc-biologic-pa-2026.pdf",
    },
  },
  {
    id: "cigna-humira",
    payer: "Cigna",
    drugName: "Humira",
    rxNormCode: "RxNorm:327361",
    coverageStatus: "Not Covered",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["M06.9", "L40.0", "K50.90"],
    criteria: {
      trialDuration: "N/A — Brand excluded from formulary",
      labRequirements: ["N/A"],
      ageLimit: "N/A",
      diagnosisRequirement: "Must use preferred biosimilar (Hadlima or Hyrimoz). Brand excluded effective 1/1/2026.",
      additionalNotes: "Exception process available only for documented medical necessity with biosimilar failure/contraindication.",
      sourceSnippet: "Cigna Drug List Update 2026: Adalimumab (Humira) — REMOVED from formulary. Replaced by preferred biosimilars Hadlima (NDC: xxxxx) and Hyrimoz (NDC: xxxxx). Exception via clinical review only.",
      sourceDocLink: "#cigna-formulary-update-2026.pdf",
    },
  },
  // Ocrevus
  {
    id: "aetna-ocrevus",
    payer: "Aetna",
    drugName: "Ocrevus",
    rxNormCode: "RxNorm:1927830",
    coverageStatus: "Prior Auth Required",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["G35"],
    criteria: {
      trialDuration: "No prior therapy trial required for PPMS; RRMS requires 1 failed DMT",
      labRequirements: ["Hepatitis B screening", "Immunoglobulin levels", "Vaccination status review"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "Confirmed MS diagnosis by McDonald criteria; MRI evidence required",
      additionalNotes: "Infusion must be at certified center. 6-month dosing cycle.",
      sourceSnippet: "Aetna MS Management 2026: Ocrelizumab — PA required. PPMS: first-line eligible. RRMS: 1 prior DMT failure. Hep B screen mandatory. Reauth q12 months.",
      sourceDocLink: "#aetna-ms-policy-2026.pdf",
    },
  },
  {
    id: "uhc-ocrevus",
    payer: "UHC",
    drugName: "Ocrevus",
    rxNormCode: "RxNorm:1927830",
    coverageStatus: "Covered with Limits",
    effectiveDate: "2026-03-01",
    diagnosisCodes: ["G35"],
    criteria: {
      trialDuration: "Must fail 2 prior DMTs (e.g., Tecfidera, Gilenya) for RRMS; PPMS first-line",
      labRequirements: ["Hepatitis B/C panel", "JC virus antibody test", "CD19/CD20 counts"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "Neurologist confirmation required; MRI within 6 months",
      additionalNotes: "Limited to 96 weeks initially. Extension requires documented EDSS stability.",
      sourceSnippet: "UHC Neurology PA Criteria 2026: Ocrelizumab — Step therapy for RRMS (2 DMT failures). PPMS first-line approved. JCV antibody required pre-initiation. Max 96 weeks initial approval.",
      sourceDocLink: "#uhc-neuro-criteria-2026.pdf",
    },
  },
  {
    id: "cigna-ocrevus",
    payer: "Cigna",
    drugName: "Ocrevus",
    rxNormCode: "RxNorm:1927830",
    coverageStatus: "Preferred",
    effectiveDate: "2025-10-01",
    diagnosisCodes: ["G35"],
    criteria: {
      trialDuration: "No step therapy required",
      labRequirements: ["Hepatitis B screening"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "MS diagnosis confirmed; all subtypes eligible",
      additionalNotes: "Preferred infusion biologic. No time limits on therapy duration.",
      sourceSnippet: "Cigna Specialty Formulary 2025-2026: Ocrelizumab — Preferred. No step therapy. Hep B screen pre-treatment. Unlimited duration with active diagnosis.",
      sourceDocLink: "#cigna-specialty-formulary-2026.pdf",
    },
  },
  // Stelara
  {
    id: "aetna-stelara",
    payer: "Aetna",
    drugName: "Stelara",
    rxNormCode: "RxNorm:897122",
    coverageStatus: "Prior Auth Required",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["L40.0", "K50.90"],
    criteria: {
      trialDuration: "Must fail 1 TNF inhibitor (e.g., Humira biosimilar) for psoriasis",
      labRequirements: ["TB screening", "Hepatitis panel"],
      ageLimit: "12 years and older for psoriasis; 18+ for Crohn's",
      diagnosisRequirement: "Moderate-to-severe plaque psoriasis (BSA ≥ 10%) or moderate-to-severe Crohn's disease",
      additionalNotes: "Weight-based dosing for Crohn's induction. Reauth annually.",
      sourceSnippet: "Aetna Dermatology/GI Policy 2026: Ustekinumab (Stelara) — PA required. Psoriasis: 1 TNF failure. Crohn's: may be first-line biologic with conventional therapy failure. Reauth q12m.",
      sourceDocLink: "#aetna-derm-gi-2026.pdf",
    },
  },
  {
    id: "uhc-stelara",
    payer: "UHC",
    drugName: "Stelara",
    rxNormCode: "RxNorm:897122",
    coverageStatus: "Step Therapy",
    effectiveDate: "2026-01-15",
    diagnosisCodes: ["L40.0", "K50.90"],
    criteria: {
      trialDuration: "Must fail 2 TNF inhibitors for psoriasis; 1 TNF for Crohn's",
      labRequirements: ["TB screening", "CBC"],
      ageLimit: "18 years and older",
      diagnosisRequirement: "Documented BSA ≥ 10% or CDAI ≥ 220",
      additionalNotes: "Step through 2 TNF agents for derm indications. Crohn's more lenient. Quantity limits apply.",
      sourceSnippet: "UHC Step Therapy Protocol ST-DERM-2026: Ustekinumab — Step 1: 2 TNF inhibitors (psoriasis) or 1 TNF (Crohn's). Step 2: Stelara. PASI/BSA documentation required. QL: per label dosing.",
      sourceDocLink: "#uhc-step-therapy-2026.pdf",
    },
  },
  {
    id: "cigna-stelara",
    payer: "Cigna",
    drugName: "Stelara",
    rxNormCode: "RxNorm:897122",
    coverageStatus: "Covered with Limits",
    effectiveDate: "2026-01-01",
    diagnosisCodes: ["L40.0", "K50.90"],
    criteria: {
      trialDuration: "Must fail 1 preferred IL-17 inhibitor (e.g., Cosentyx) for psoriasis",
      labRequirements: ["TB screening"],
      ageLimit: "6 years and older",
      diagnosisRequirement: "Moderate-to-severe disease per clinical criteria",
      additionalNotes: "Non-preferred biologic. IL-17 inhibitor preferred for psoriasis. No step for Crohn's.",
      sourceSnippet: "Cigna Biologic Tiering 2026: Ustekinumab — Non-preferred. Psoriasis: IL-17 trial required. Crohn's: no step therapy. PA required. Age 6+ per label.",
      sourceDocLink: "#cigna-biologic-tiering-2026.pdf",
    },
  },
];

export const PAYER_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  Aetna: { bg: "bg-purple-100", text: "text-purple-900", border: "border-purple-300" },
  UHC: { bg: "bg-orange-100", text: "text-orange-900", border: "border-orange-300" },
  Cigna: { bg: "bg-teal-100", text: "text-teal-900", border: "border-teal-300" },
};

export const DEFAULT_PAYER_STYLE = {
  bg: "bg-slate-100",
  text: "text-slate-900",
  border: "border-slate-300",
};

export const STATUS_STYLES: Record<CoverageStatus, { bg: string; text: string; icon: string }> = {
  Preferred: { bg: "bg-emerald-100", text: "text-emerald-900", icon: "\u2713" },
  "Prior Auth Required": { bg: "bg-amber-100", text: "text-amber-900", icon: "\u26A0" },
  "Step Therapy": { bg: "bg-blue-100", text: "text-blue-900", icon: "\u21A3" },
  "Not Covered": { bg: "bg-red-100", text: "text-red-900", icon: "\u2717" },
  "Covered with Limits": { bg: "bg-sky-100", text: "text-sky-900", icon: "\u25D4" },
};

// ── Version History / Policy Changes mock data ──

export const QUARTERS: QuarterOption[] = [
  { value: "2026-Q2", label: "Q2 2026 (Apr–Jun)" },
  { value: "2026-Q1", label: "Q1 2026 (Jan–Mar)" },
  { value: "2025-Q4", label: "Q4 2025 (Oct–Dec)" },
  { value: "2025-Q3", label: "Q3 2025 (Jul–Sep)" },
];

export const MOCK_POLICY_CHANGES: PolicyChange[] = [
  {
    id: "chg-1",
    payer: "Aetna",
    drugName: "Keytruda",
    field: "Trial Duration",
    oldValue: "Must have failed 6-month trial of standard chemotherapy",
    newValue: "Must have failed 3-month trial of standard chemotherapy",
    changeType: "modification",
    effectiveDate: "2026-01-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-2",
    payer: "Cigna",
    drugName: "Humira",
    field: "Coverage Status",
    oldValue: "Step Therapy",
    newValue: "Not Covered (brand excluded from formulary)",
    changeType: "removal",
    effectiveDate: "2026-01-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-3",
    payer: "UHC",
    drugName: "Ocrevus",
    field: "Lab Requirements",
    oldValue: "Hepatitis B/C panel; JC virus antibody test",
    newValue: "Hepatitis B/C panel; JC virus antibody test; CD19/CD20 counts",
    changeType: "addition",
    effectiveDate: "2026-03-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-4",
    payer: "UHC",
    drugName: "Keytruda",
    field: "Reauthorization Frequency",
    oldValue: "Re-authorization every 12 months",
    newValue: "Re-authorization every 6 months with imaging",
    changeType: "modification",
    effectiveDate: "2026-01-15",
    quarter: "2026-Q1",
  },
  {
    id: "chg-5",
    payer: "Aetna",
    drugName: "Humira",
    field: "Step Therapy Requirement",
    oldValue: "Step through 1 conventional DMARD",
    newValue: "Step through methotrexate + 1 DMARD, then preferred biosimilar before brand",
    changeType: "modification",
    effectiveDate: "2026-01-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-6",
    payer: "Cigna",
    drugName: "Keytruda",
    field: "Age Limit",
    oldValue: "18 years and older",
    newValue: "12 years and older (pediatric indications included)",
    changeType: "modification",
    effectiveDate: "2025-07-01",
    quarter: "2025-Q3",
  },
  {
    id: "chg-7",
    payer: "Cigna",
    drugName: "Ocrevus",
    field: "Coverage Status",
    oldValue: "Prior Auth Required",
    newValue: "Preferred (PA waived)",
    changeType: "modification",
    effectiveDate: "2025-10-01",
    quarter: "2025-Q4",
  },
  {
    id: "chg-8",
    payer: "UHC",
    drugName: "Stelara",
    field: "Step Therapy TNF Requirement",
    oldValue: "Must fail 1 TNF inhibitor for psoriasis",
    newValue: "Must fail 2 TNF inhibitors for psoriasis; 1 TNF for Crohn's",
    changeType: "modification",
    effectiveDate: "2026-01-15",
    quarter: "2026-Q1",
  },
  {
    id: "chg-9",
    payer: "Aetna",
    drugName: "Stelara",
    field: "Crohn's Disease Coverage",
    oldValue: "Not covered for Crohn's disease",
    newValue: "May be first-line biologic with conventional therapy failure for Crohn's",
    changeType: "addition",
    effectiveDate: "2026-01-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-10",
    payer: "Cigna",
    drugName: "Stelara",
    field: "Preferred Biologic Tier",
    oldValue: "Preferred biologic, no step therapy",
    newValue: "Non-preferred; must trial IL-17 inhibitor first for psoriasis",
    changeType: "modification",
    effectiveDate: "2026-01-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-11",
    payer: "UHC",
    drugName: "Ocrevus",
    field: "Therapy Duration Limit",
    oldValue: "No explicit duration limit",
    newValue: "Limited to 96 weeks initially; extension requires documented EDSS stability",
    changeType: "addition",
    effectiveDate: "2026-03-01",
    quarter: "2026-Q1",
  },
  {
    id: "chg-12",
    payer: "Aetna",
    drugName: "Keytruda",
    field: "PD-L1 Threshold",
    oldValue: "PD-L1 expression ≥ 1% (any positive)",
    newValue: "PD-L1 expression ≥ 50% (TPS) via FDA-approved companion diagnostic",
    changeType: "modification",
    effectiveDate: "2025-10-01",
    quarter: "2025-Q4",
  },
];
